#pragma once
#include <new>
#include <windows.h>
#include <cstdio>
#include "CallbackTree.h"
#include "ClassDmsplayer.h"
#include "D2D1DrawFactory.h"
#include "DoubleThreadLock.h"
#include "DynamicGraphD2D1.h"
#include "FastSchedule.h"
#include "FileResourceManager.h"
#include "GameObject2D.h"
#include "GridSelector.h"
#include "KeyFunctionMap.h"
#include "MathList.h"
#include "McsJudge.h"
#include "TextFormatFactory.h"
#include "TimeVariantObject.h"